name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Gideon ${{ github.ref }}
          draft: false
          prerelease: false

  build-and-release:
    name: Build and Release
    needs: create-release
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            artifact: '*.AppImage'
          - os: windows-latest
            platform: windows
            artifact: '*.exe'
          - os: macos-latest
            platform: macos
            artifact: '*.dmg'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build application
        run: npm run build
        
      - name: Package Electron app
        run: npm run build:all
        
      - name: Get package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: release/gideon-${{ steps.package-version.outputs.current-version }}-${{ matrix.platform }}.${{ matrix.artifact }}
          asset_name: gideon-${{ steps.package-version.outputs.current-version }}-${{ matrix.platform }}.${{ matrix.artifact }}
          asset_content_type: application/octet-stream